### ISSUE TITLE
TestTask. Windows. Absent `HOMEDRIVE` and `HOMEPATH` environment variables

### ISSUE THREAD

**Issue by romanmikhailov** [eliasku/hxmake#30]
Environment variables `HOMEDRIVE`, `HOMEPATH` is absent on my system.

Windows 10 (10.0)

Required for TestTask (target=swf).

**Comment by romanmikhailov** [comment]
I suggest the same behavior as in `haxelib`:
https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/client/Main.hx#L989

**Comment by eliasku** [comment]
please check `develop`
